apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainwave
  labels:
    app: brainwave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brainwave
  template:
    metadata:
      labels:
        app: brainwave
    spec:
      containers:
      - name: brainwave
        image: pradeepkumavat/brainwave:latest

---

apiVersion: v1
kind: Service
metadata:
  name: service-brainwave
spec:
  selector:
    app: brainwave
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 5173